FROM node:alpine

ENV NODE_OPTIONS=--openssl-legacy-provider

WORKDIR /frontreact
COPY package*.json . 

RUN npm install --silent
RUN npm install react-scripts@3.0.1 -g --silent


EXPOSE 3000

CMD npm start